# Generated by Django 4.1.2 on 2022-10-25 20:13

from django.db import migrations, models
import metabase_wrapper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SkuDirty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sku', models.ForeignKey(on_delete=models.SET(metabase_wrapper.models.get_default_sku), to='metabase_wrapper.sku')),
            ],
        ),
    ]
