# Generated by Django 4.1.2 on 2022-10-25 20:36

from django.db import migrations, models
import metabase_wrapper.models


class Migration(migrations.Migration):

    dependencies = [
        ('metabase_wrapper', '0002_alter_sku_table_alter_skudirty_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skudirty',
            name='sku',
            field=models.ForeignKey(default=metabase_wrapper.models.get_default_sku, on_delete=models.SET(metabase_wrapper.models.get_default_sku), to='metabase_wrapper.sku'),
        ),
    ]
