# Generated by Django 4.1.2 on 2022-10-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabase_wrapper', '0003_alter_skudirty_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='skudirty',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
