# Generated by Django 4.1.2 on 2022-11-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabase_wrapper', '0004_alter_sku_name_alter_skudirty_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Дистрибьютор',
                'verbose_name_plural': 'Дистрибьюторы',
                'db_table': 'distributor',
            },
        ),
        migrations.CreateModel(
            name='SOFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=250, unique=True)),
                ('upload', models.FileField(upload_to='so_files/')),
            ],
            options={
                'verbose_name': 'Файлы SO',
                'verbose_name_plural': 'Файлы SO',
                'db_table': 'so_file',
            },
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'verbose_name': 'SKU', 'verbose_name_plural': 'SKU'},
        ),
        migrations.AlterModelOptions(
            name='skudirty',
            options={'verbose_name': 'Dirty SKU', 'verbose_name_plural': 'Dirty SKU'},
        ),
    ]
