# Generated by Django 4.1.3 on 2022-11-06 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metabase_wrapper', '0006_distributorgroup_distributor_operation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofile',
            name='distriutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metabase_wrapper.distributor'),
        ),
    ]
