# Generated by Django 4.1.3 on 2022-11-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metabase_wrapper', '0007_sofile_distriutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sofile',
            old_name='distriutor',
            new_name='distributor',
        ),
    ]
