# Generated by Django 4.1.3 on 2022-11-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metabase_wrapper', '0009_channel1_channel2_department_format1_format2_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='address',
        ),
    ]
