# Generated by Django 4.1.3 on 2022-11-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metabase_wrapper', '0010_remove_manager_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='department',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='head',
        ),
        migrations.CreateModel(
            name='ManagerDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metabase_wrapper.department')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metabase_wrapper.manager')),
            ],
            options={
                'db_table': 'manager_department',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ManyToManyField(related_name='departments', through='metabase_wrapper.ManagerDepartments', to='metabase_wrapper.manager'),
        ),
    ]
