# Generated by Django 4.1.3 on 2022-11-06 20:47

from django.db import migrations, models
import metabase_wrapper.models


class Migration(migrations.Migration):

    dependencies = [
        ('metabase_wrapper', '0011_remove_manager_department_remove_manager_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofile',
            name='is_month_inside',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sofile',
            name='month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=metabase_wrapper.models.current_month),
        ),
        migrations.AddField(
            model_name='sofile',
            name='year',
            field=models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=metabase_wrapper.models.current_year),
        ),
    ]
